Updated to version 3.65.3 (3.65.X RC 1)

diff --git a/HMserver/etc/init.d/S62HMServer b/HMserver/etc/init.d/S62HMServer
--- a/HMserver/etc/init.d/S62HMServer
+++ b/HMserver/etc/init.d/S62HMServer
@@ -5,56 +5,75 @@
 
 LOGLEVEL_HMServer=5
 CFG_TEMPLATE_DIR=/etc/config_templates
-PIDFILE=/var/run/HMIPServer.pid
 STARTWAITFILE=/var/status/HMServerStarted
+PIDFILE=/var/run/HMIPServer.pid
 CLAZZPATH=$(find /opt/HMServer/ -type f -name "*.jar" | xargs echo | sed s/' '/':'/g)
 
+
 init() {
-	export TZ=`cat /etc/config/TZ | cut -d'-' -f1 | cut -d'+' -f1`
-	export JAVA_HOME=/opt/jre
-	export PATH=$PATH:$JAVA_HOME/bin
-	if [ ! -e /etc/config/log4j.xml ] ; then
-		cp $CFG_TEMPLATE_DIR/log4j.xml /etc/config
-	fi
-	if [ ! -e /etc/config/hmip_networkkey.conf ] ; then
-		cp $CFG_TEMPLATE_DIR/hmip_networkkey.conf /etc/config
-	fi
+  export JAVA_HOME=/opt/java/
+  export PATH=${PATH}:${JAVA_HOME}/bin
+
+  if [[ ! -e /etc/config/log4j2.xml ]]; then
+    cp -a ${CFG_TEMPLATE_DIR}/log4j2.xml /etc/config
+  fi
+
+  if [[ ! -e /etc/config/hmip_networkkey.conf ]]; then
+    if [[ -f ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf ]]; then
+      cp -a ${CFG_TEMPLATE_DIR}/hmip_networkkey.conf /etc/config
+    fi
+  fi
+}
+
+waitStartupComplete() {
+  STEPS=150
+  for i in $(seq 1 ${STEPS}); do
+    sleep 2
+    echo -n "."
+    if [[ -e ${STARTWAITFILE} ]]; then
+      echo "OK"
+      break
+    fi
+    if [[ ${i} -eq ${STEPS} ]]; then
+      echo "ERROR"
+    fi
+  done
 }
 
 start() {
-	echo -n "Starting HMServer: "
-	init
-	start-stop-daemon -S -q -m -p $PIDFILE --exec java -- -Xmx64m -Dlog4j.configuration=file:///etc/config/log4j.xml -Dfile.encoding=ISO-8859-1 -cp $CLAZZPATH de.eq3.ccu.server.ip.HMIPServer /etc/crRFD.conf &
-	echo "Waiting for HMServer to get ready"
-	eq3configcmd wait-for-file -f $STARTWAITFILE -p 5 -t 600
-	echo "OK"
+  echo -n "Starting HMIPServer: "
+  init
+  start-stop-daemon -b -S -q -m -p ${PIDFILE} --exec java -- -Xmx128m -Dos.arch=arm -Dlog4j.configurationFile=file:///etc/config/log4j2.xml -Dfile.encoding=ISO-8859-1 -Dgnu.io.rxtx.SerialPorts=/dev/mmd_hmip -cp ${CLAZZPATH} de.eq3.ccu.server.ip.HMIPServer /etc/crRFD.conf /etc/HMServer.conf
+  echo -n "."
+  waitStartupComplete
 }
+
 stop() {
-	echo -n "Stopping HMServer: "
-	rm -f $STARTWAITFILE
-	start-stop-daemon -K -q -p $PIDFILE
-	rm -f $PIDFILE
-	echo "OK"
+  echo -n "Stopping HMIPServer: "
+  rm -f ${STARTWAITFILE}
+  start-stop-daemon -K -q -p ${PIDFILE}
+  rm -f ${PIDFILE}
+  echo "OK"
 }
+
 restart() {
-	stop
-	start
+  stop
+  start
 }
 
 case "$1" in
   start)
-	start
-	;;
+    start
+  ;;
   stop)
-	stop
-	;;
+    stop
+  ;;
   restart|reload)
-	restart
-	;;
+    restart
+  ;;
   *)
-	echo "Usage: $0 {start|stop|restart}"
-	exit 1
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
 esac
 
 exit $?
-
